more bazel config
hash was wrong

next error:
The fix is simple: since there is no common prefix to strip, we must remove that attribute from the rule.

bazel build //src:blazeface_hermetic
INFO: Repository +litert_deps+bazel_skylib instantiated at:
  <builtin>: in <toplevel>
Repository rule http_archive defined at:
  /home/kiel/.cache/bazel/_bazel_kiel/615104dec347003ca785b8d0b0a671f7/external/bazel_tools/tools/build_defs/repo/http.bzl:431:31: in <toplevel>
ERROR: /home/kiel/.cache/bazel/_bazel_kiel/615104dec347003ca785b8d0b0a671f7/external/bazel_tools/tools/build_defs/repo/http.bzl:155:45: An error occurred during the fetch of repository '+litert_deps+bazel_skylib':
   Traceback (most recent call last):
        File "/home/kiel/.cache/bazel/_bazel_kiel/615104dec347003ca785b8d0b0a671f7/external/baz